const conf = require("../../../../src/configs/sunucuayar.json");
const { boosterRolu } = conf; // Destructure for easy access
const xdxd = [
    "Çok pahalisin be mutluluk...",
    "Vefasiz, karanlik yolda hosça kal diyendir!",
    "Gitsem ayrilik kalsam yalnizlik.",
    "Ben sadece yoldum. Sen beni hep kaybettin.",
    "Hangi mevsimin rüzgaridir ask? Ne yana dönsem yüzüme hüzün eser.",
    "Etrafim çok kalabalik ama hepsi merhabalik.",
    "En çok beni sevseydin böyle olmazdi biliyorum.",
    "Efkarin demir attigi liman yürektir.",
    "Hadi yalnizligini idam et bakalim, son arzusunu yerine getirebilecek misin?",
    "Herkesten yakin olmak istedigin insana, uzaktan bakmak çok zor.",
    "Kolay degildir; ugruna her seyinizi verdiginiz insana yabanci gibi bakmak.",
    "Hüznün baskenti gibisin yüregim, özür dilerim seni bu hale getirdigim için!",
    "Yüregiyle gelmeyen bahanesiyle gelir.",
    "Ikimizin adi bir cümlede geçmediginden beri ilgimi çekmiyor kimin ne söyledigi.",
    "Tespih gibi oldu acilarim çektikçe basa dönüyorum.",
    "Okudugum kitaplarda buldugum aski, tanidigim ve güvendigim insanlarda kaybettim.",
    "Gönlüm deniz degil ki efkarim sahile vursun.",
    "Gönül yorgun düstügünde, yürek dilsiz kalir.",
    "Ölümden sonrasi varken. Senden sonrasi neden olmasin sevgili…",
    "Bütün insanlari sevebilirdim, sevmeye senden baslamasaydim.",
    "Bugün biraz efkarliyim, nedenini bilmiyorum. Öyle daliyorum bos bos. Bir tek seni düsünüyorum.",
    "Seni degil, bizi geri istiyorum!",
    "En son utanacagin sey aglamak olsun.",
    "Geçmise sünger çek. Gelecege emin bak. Inan gelecekte seni ne firsatlar bekliyor olacak.",
    "Beni unutma olur mu? Gezdigimiz o yerleri, el ele tutustugumuz ilk parki. Unutulmak dokunur çünkü insana.",
    "Sevmek, hesap isi degil, sevmek güvenmekti, ait olmakti. Eskidendi.",
    "Efkarli olmak, birazda sitemkar, Ben hepsini topladim bir araya. Galiba yaslaniyorum. Gene tek basimayim.",
    "Gitmek istedigin yere vardin biliyorum, olsun ben hala varmissin gibi yapiyorum.",
    "Bu kez anladim hüzünlerden bozma mutluluklar yasiyorum.",
    "Payimiza sükut düstügünden beridir, kalbimizin sesini daha bir güzel duyar olduk!",
    "Bazen gözlerden yas akmaz kalp aglar sadece.",
    "En kötüsü de etrafa renk saçarken, kendi içinde siyah olmak.",
    "Bitiyor benim için bu gece hayat son kez gözlerine bakip aglamak isterdim sevdigim.",
    "Kabullenmek kendi mezarina toprak atmak gibidir bazen.",
    "Ay degil, mevsim degil, bir ömür geçti sensiz, keske böyle sevmeseydim agliyorum çaresiz.",
    "Beraber gülmeyi özledigimiz insanlar, simdi baskalariyla kahkahalarin dibine vuruyor.",
    "Gidecek yerin kalmadiginda zoruna gider hayat.",
    "Seni aklima getirecek birçok sarki varken, yanima getirecek hiçbir sey yok.",
    "Tutacak bir el yoksa sikinti yok, biz de elimizi cebimize koyar yürürüz.",
    "Biraktigin düsü kim büyütecek simdi?",
    "Bir gün bir yerde karsilasirsak birbirimizle yeniden tanisalim.",
    "Bütün asklar bir rüya gibi basliyor, kabus gibi sona eriyor.",
    "Yüregim seni bu hale getirdigim için özür dilerim.",
    "Bazen sadece yürek aglar, gözlerden yas akmaz.",
    "Gidecek yerin kalmadigi zaman hayat zoruna gider.",
    "Içimi dökmeye hiç niyetim yok, zaten zor sigdirmisim.",
    "Her geçen gün biraz daha uzaklasiyorum senden, ama hala seni seviyorum.",
    "Birinin kalbine girmek kolaydir, ama o kalpte kalabilmek zor.",
    "Bazen en güzel anilar, en aci hatiralardan dogar.",
    "Ask, ne kadar yakinimda olsa da bazen ulasilmaz olur.",
    "Birlikte yasadikça kaybolan hisler, zamanla daha da derinlesir.",
    "Birlikte yudumladigimiz çay bile seni hatirlatiyor.",
    "Kalbim seni seviyor, ama aklim hep gitmek istiyor.",
    "Hep bir eksik parça gibi hissediyorum, belki de sensin o parça.",
    "Geceyi seninle geçirmeyi hayal ediyorum, ama hep yalnizim.",
    "Bazen yalnizlik, en yakin arkadasin olur.",
    "Biri seni sevmeden gitmisse, bile bile seversin onu.",
    "Zamanla her sey degisir, ama hatiralar hep ayni kalir.",
    "Bazen sevdiklerin bile, seni en çok incitenler olabilir.",
    "Seninle geçen her an, yillara bedel.",
    "Içimdeki boslugu doldurmanin tek yolu sensin.",
    "Aglamak bazen bir insanin içindeki en güzel duygudur.",
    "Zaman, aciyi unutturur ama hatiralari silmez.",
    "Sonsuza kadar unutmak için, ilk adimi atman gerekir.",
    "Birine olan sevgini dile getiremedigin zaman, kalbinde bir yara açilir.",
    "Bazen kaybettigini sandigin sey, aslinda seni bulmana sebep olur.",
    "Gerçek ask, bazen sadece ayrilikta anlasilir.",
    "Birinin gözlerine bakarken, tüm dünyayi kaybetmis gibi hissedebilirsin.",
    "Sadece seni görmek istiyorum, ama seni görememek en zor sey.",
    "Sevmenin bedeli, bazen kaybetmek olur.",
    "Bir tek seni sevmedim, bütün zamanlari sana ayirdim.",
    "Bazen kalbinin sesini duymak, her seyden daha degerlidir.",
    "Huzur, seninle olmak, bir ömre bedel.",
    "Belki de tek istedigim, seninle olabilmekti.",
    "Eger bir gün seni kaybedersem, kaybettigimi anladigim an, seni geri bulurum.",
    "Bazen, en büyük aci, birine veda etmek zorunda kalmaktir.",
    "Ask, sadece iki kisi arasinda bir bag degildir, bazen içsel bir huzurdur.",
    "Beni unut, ama seni her zaman hatirlayacagim.",
    "Bazen seni sevmenin acisi, beni çok yorar.",
    "Sonsuzluga giden yolda, seninle olmak isterdim.",
    "Hep yanimda olsan da, içimdeki boslugu bir türlü dolduramiyorum.",
    "Sonsuzluk, sadece seninle anlam kazanir.",
    "Bir zamanlar seninle olan her sey, simdi sadece anilarda kaliyor.",
    "Birinin kayboldugu yeri aramak, hayatin anlamini bulmak gibidir.",
    "Hayat, bazen kaybolan birini bulmaya çalismaktir.",
    "Bir gün geçer, ama bugün hala seni düsünüyorum.",
    "Hayat, küçük anlarda kaybolan büyük duygulardir.",
    "Sevdanin gücü, kalbinde hissettikçe artar.",
    "Bazen en güzel sey, seni düsünmektir.",
    "Bitti dedigim her sey, bir baslangicin habercisidir.",
    "Zamanla her sey degisir, ama içimdeki sen hep kalir.",
    "Herkes bir gün terk eder, ama sevdanin yerini kimse alamaz.",
    "Bazen susmak, her seyin en güzel cevabidir.",
    "Zihnimdeki sesler, hep seni arar.",
    "Birini kaybetmek, aslinda kendini bulmaktir.",
    "Bazen en karanlik geceler, en parlak yildizlari getirir.",
    "Sonsuza kadar sevmek, aslinda bazen sadece ani hatirlamaktir.",
    "Birbirimizi kaybettik ama ben hep seni düsündüm.",
    "Içimdeki boslugu seninle doldurmak istiyorum.",
    "Bazen sadece susarak, her seyi anlatmak yeterlidir.",
    "Bir an için bile olsa, birlikte olmak ne kadar güzel.",
    "Kalbinin ritmi, artik senin adini fisildiyor.",
    "Gözlerinde kayboldugum ani hatirliyorum, zaman durdu o an.",
    "Hüzün, bazen kalbin en güzel melodisidir.",
    "Birlikte oldugumuz her an, bir ömre bedeldi.",
    "Kalbim seni seviyor, ama kelimeler yetmiyor.",
    "Biraz daha gülümsesen, dünya bile sana gülerdi.",
    "Beni terk ettin, ama hala seni seviyorum.",
    "Herkes zamanla unutulsa da, seni unutmak bir ömür alir.",
    "Bir gün seni sevmek zorunda kalacagim, ama o an geldiginde çok geç olacak.",
    "Birlikte yasadigimiz anlarin degerini zamaninda anlamadim.",
    "Hayat, bazen kayboldugunuz yeri bulmaktir.",
    "Bir gün geri döndügünde, seni bekliyor olacagim.",
    "Her adimda seni hissetmek, en güzel yolculuk olurdu.",
    "Birbirimize kayboldugumuz ani tekrar yasayabilmeyi isterdim.",
    "Bazen en güzel duygular, en fazla aciyi getirir.",
    "Beni terk ettiginde bile, seninle yasadim her ani.",
    "Bir zamanlar sevdikçe kayboldugumuz, simdi hatirladikça kayboldugumuz yerler.",
    "Içimdeki bosluk her geçen gün daha da büyüyor, belki de senin yerin.",
    "Birlikte geçirdigimiz zaman, her seyin ötesindeydi.",
    "Hayat, seninle güzel ama sensiz çok zor."
];

module.exports = {
    conf: {
        aliases: [],
        name: "yak",
        help: "yak",
        category: "eglence",
    },

    run: async (client, message, args, embed, prefix) => {
        // Ensure booster role is configured
        if (!boosterRolu) {
            return message.reply({ content: "Booster Rolu Bulunamadi!" }).then((e) => setTimeout(() => e.delete(), 5000));
        }
    
        // Check if the user has the booster role or is an admin
        if (!message.member.roles.cache.has(boosterRolu) && !message.member.permissions.has("ADMINISTRATOR")) {
            return message.reply({ content: "Bu Komutu Kullanabilmek Için Booster Rolüne Sahip Olmalisin veya Admin Yetkin Olmali!" }).then((e) => setTimeout(() => e.delete(), 5000));
        }
    
        // Select a random quote
        const randomQuote = xdxd[Math.floor(Math.random() * xdxd.length)];
        
        // Send the embed with the random quote
        await message.channel.send({ embeds: [embed.setDescription(randomQuote)] });
    }
}